### ISSUE TITLE
Failed install attempts

### ISSUE THREAD

**Issue by kevosomi** [thekordy/ticketit#179]
Hello Developer!

Great package. I have used it once before but as of now I am trying to install it and I keep on getting redirected to my homepage. I have a roles table with the following types: admin, client, writer, and agents. Please guide me on how to go about it. 

Thank you in advance.

Regards,

Kelvin

**Comment by thekordy** [comment]
Thank you.

I just released a bug fixes release v0.2.5 .. try to reinstall the package (and drop ticketit tables or rollback the ticketit migrations) and make sure you are logged in with the user id 1 when you visit ticketit or ticketit-install for the first time.

**Comment by kevosomi** [comment]
Alright, let me do that now and get back to you shortly.

**Comment by kevosomi** [comment]
It is still not working, redirects me to the homepage. When I try to visit http://project/ticketit I am getting the error NotFoundHttpException in RouteCollection.php line 161

Further, when I attempt to publish the config file, I get the reply that there's nothing to publish

**Comment by aaronkramer** [comment]
I am also getting the same issue as kevosomi
